### ISSUE TITLE
Load Random Game not working?

### ISSUE THREAD

**Issue by ImSpecial** [SourMesen/Mesen#451]
So this feature sounds super cool but when I try to use it "Ctrl+Insert" by default or Tools > Load Random Game, I get a popup that says "Mesen could not find any game to load."

I have Mesen pointed to the right ROM directory with the Folder Override, and when I go File > Open, it takes me to the correct folder...

Any idea?

**Comment by SourMesen** [comment]
The random game feature relies on the recently loaded file list to find folders that have games (since setting a rom folder is entirely optional).  Maybe your recent file list is empty?

That said, it would make sense for it to also check the rom folder, if one is set.

**Comment by ImSpecial** [comment]
Yeah my recent file list is cleared, so that must be it... Mystery solved!

**Comment by ImSpecial** [comment]
I know I closed this pretty hastily once I figure out why it was doing what it was doing, but as you say, it  make sense for it to also check the rom folder, if one is set.

So can I request this to be added as a new feature/enhancement in a later version?

Thanks and hope you see this :P

**Comment by SourMesen** [comment]
This is fixed by ec60b530593d65a196f2d77bbb87eae2bd175ada
If a game folder is specified, the load random game option will always try to load games from it (and its subfolders) and nowhere else.

**Comment by ImSpecial** [comment]
Thanks! 0.9.6 didn't last long. :P

**Comment by ImSpecial** [comment]
Sorry to bump this, but this still isn't working for me in the latest release 0.9.7.

**Comment by SourMesen** [comment]
I can't reproduce this on 0.9.7 on my end.

With a folder config that looks like this (don't mind the ¥ signs, that's just how backslashes are displayed when setting Windows to the Japanese locale..):
![image](https://user-images.githubusercontent.com/21093973/45620890-50c26c80-ba4c-11e8-9d88-47885b99f649.png)

And no files in the "Recent files" menu, clicking on the "Load random game" button does load a random game from the specified folder, even if the folder only contains subfolders (which in turn contain roms)

**Comment by ImSpecial** [comment]
This is what mine is, and looks similar to yours. 
https://i.imgur.com/jyaywqZ.png

And even after playing a game or two to populate the "Recent files" menu, I still get the same message that Mesen could not find any games to load.

Here is my settings file if that will help you.

settings.xml
https://www30.zippyshare.com/v/6MGk5Ko2/file.html

**Comment by SourMesen** [comment]
I can't reproduce this even using your config file and the exact same folder.

But, I just thought of a possibility - does your folder actually contain .nes/.fds files? If all the roms are zipped (zip/7z), it won't work.  Making it load random games from within archives would be pretty mean on the disk (since it would require opening any and all archives, checking if nes roms are contained within them, etc.)

**Comment by ImSpecial** [comment]
Oh that must be it then, all of my ROMs are inside a ".zip" file by the same name as the ROM that sits inside.

**Comment by SourMesen** [comment]
I tweaked the logic a bit in 420fb9c050ffaf2af8ff4f408af0890f7fe77716.

Basically, it will now try to load random zip/7z files to see if there are any .nes/.fds files in them, if there are none, it will try loading another file instead (it will try up to 5 files this way before giving up).

If it ends up trying 5 files that don't contain roms, nothing will happen (but this shouldn't really ever happen in practice).

It will currently only try loading the first rom file in any archive, rather than a random rom inside of it (could probably have made that random too, but not really an issue in most cases, I would imagine)

Here's a dev build with the fix: https://ci.appveyor.com/api/buildjobs/c3b83480jm50rvht/artifacts/MesenDevWin-0.9.7.1.exe
This won't be in any official release until 2019, most likely, so you'll probably want to use that build if you really want that feature to work :p

**Comment by ImSpecial** [comment]
Very cool, I gave that dev build a test and it works as expected now, and as expected it a very cool feature!

Enjoy your holiday.

**Comment by SourMesen** [comment]
Thanks!
